import Fuse from 'fuse.js'
import type { ToolMeta } from '@toolbox/types/tool'

export const toolRegistry: ToolMeta[] = [
  // ─── Phase 1: 高频工具首批 (15个) ───────────────────────────────────────────

  // Format - 格式化
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    nameEn: 'JSON Formatter',
    description: '格式化、压缩、校验 JSON 数据，支持语法高亮，缩进可选',
    category: 'format',
    tags: ['json', 'format', 'validate', 'prettify', 'minify'],
    keywords: ['大括号', 'object', '对象', '压缩'],
    icon: 'Braces',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    nameEn: 'Markdown Preview',
    description: '实时渲染 Markdown，支持 GFM、数学公式、代码高亮，导出 HTML',
    category: 'format',
    tags: ['markdown', 'preview', 'md', 'gfm', 'render'],
    keywords: ['md', '文档', '渲染'],
    icon: 'FileText',
  },

  // Encoding - 编码解码
  {
    id: 'base64',
    name: 'Base64 编解码',
    nameEn: 'Base64 Encoder/Decoder',
    description: '文本 Base64/Base64URL 编解码，支持文件转 Base64',
    category: 'encoding',
    tags: ['base64', 'encode', 'decode', 'base64url'],
    keywords: ['编码', '解码', '二进制'],
    icon: 'Binary',
  },
  {
    id: 'url-encode',
    name: 'URL 编解码',
    nameEn: 'URL Encoder/Decoder',
    description: 'encodeURIComponent/完整 URL 编解码，参数解析',
    category: 'encoding',
    tags: ['url', 'encode', 'decode', 'percent', 'uri'],
    keywords: ['链接', '参数', '转义'],
    icon: 'Link',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 解析',
    nameEn: 'JWT Decoder',
    description: '解析 Header/Payload，时间戳转人类时间，高亮过期',
    category: 'encoding',
    tags: ['jwt', 'token', 'decode', 'auth', 'json web token'],
    keywords: ['令牌', '认证', '身份'],
    icon: 'KeyRound',
  },

  // Crypto - 加密安全
  {
    id: 'hash-calculator',
    name: 'Hash 计算器',
    nameEn: 'Hash Calculator',
    description: 'MD5/SHA-1/SHA-256/SHA-384/SHA-512 哈希计算，支持文本和文件',
    category: 'crypto',
    tags: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'checksum'],
    keywords: ['哈希', '摘要', '校验'],
    icon: 'Hash',
  },

  // Generator - 生成器
  {
    id: 'uuid-generator',
    name: 'UUID 生成器',
    nameEn: 'UUID Generator',
    description: 'UUID v4 批量生成（最多1000），大写/小写/带连字符可选',
    category: 'generator',
    tags: ['uuid', 'generate', 'unique', 'id', 'guid', 'v4'],
    keywords: ['唯一', '标识符', 'GUID'],
    icon: 'Fingerprint',
  },
  {
    id: 'password-gen',
    name: '密码生成器',
    nameEn: 'Password Generator',
    description: '可配置字符集、长度、数量，强度可视化，批量导出',
    category: 'generator',
    tags: ['password', 'generate', 'random', 'secure', 'strong'],
    keywords: ['密码', '随机', '安全'],
    icon: 'KeySquare',
  },

  // Datetime - 时间日期
  {
    id: 'timestamp',
    name: '时间戳转换',
    nameEn: 'Timestamp Converter',
    description: 'Unix 时间戳与日期时间互转，支持毫秒/秒，全球时区',
    category: 'datetime',
    tags: ['timestamp', 'unix', 'datetime', 'timezone', 'convert'],
    keywords: ['时间', '日期', '时区'],
    icon: 'Clock',
  },

  // Text - 文本处理
  {
    id: 'case-converter',
    name: '命名规范转换',
    nameEn: 'Case Converter',
    description: 'camelCase/PascalCase/snake_case/kebab-case/CONSTANT 等互转',
    category: 'text',
    tags: ['case', 'camel', 'snake', 'pascal', 'kebab', 'convert'],
    keywords: ['大小写', '命名', '格式'],
    icon: 'CaseSensitive',
  },
  {
    id: 'lorem-ipsum',
    name: '占位文本生成',
    nameEn: 'Lorem Ipsum Generator',
    description: '英文 Lorem/中文乱数假文，段落数/单词数可配置',
    category: 'text',
    tags: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text', '中文'],
    keywords: ['假文', '测试', '填充'],
    icon: 'AlignLeft',
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    nameEn: 'Regex Tester',
    description: '实时高亮匹配，分组提取，多行模式，常用正则库',
    category: 'text',
    tags: ['regex', 'regexp', 'test', 'match', 'pattern'],
    keywords: ['正则', '匹配', '模式'],
    icon: 'Regex',
  },
  {
    id: 'text-counter',
    name: '文本统计',
    nameEn: 'Text Counter',
    description: '字符数/单词数/行数/字节数/阅读时间估算',
    category: 'text',
    tags: ['text', 'count', 'character', 'word', 'line', 'byte'],
    keywords: ['统计', '字数', '计数'],
    icon: 'TextCursor',
  },

  // Color - 颜色设计
  {
    id: 'color-picker',
    name: '颜色选择器',
    nameEn: 'Color Picker',
    description: 'HEX/RGB/HSL/HSV/CMYK 互转，色盘可视化',
    category: 'color',
    tags: ['color', 'picker', 'hex', 'rgb', 'hsl', 'cmyk', 'convert'],
    keywords: ['颜色', '色彩', '调色'],
    icon: 'Palette',
  },

  // Converter - 单位换算
  {
    id: 'number-base',
    name: '进制转换',
    nameEn: 'Number Base Converter',
    description: '二/八/十/十六进制互转，按位操作可视化',
    category: 'converter',
    tags: ['binary', 'hex', 'octal', 'decimal', 'base', 'convert', 'radix'],
    keywords: ['二进制', '八进制', '十六进制'],
    icon: 'Binary',
  },

  // ─── Phase 2+: 后续阶段工具 ────────────────────────────────────────────────

  // Format - 格式化
  {
    id: 'yaml-json',
    name: 'YAML ↔ JSON',
    nameEn: 'YAML JSON Converter',
    description: 'YAML 与 JSON 格式互转',
    category: 'format',
    tags: ['yaml', 'json', 'convert'],
    icon: 'ArrowLeftRight',
  },
  {
    id: 'sql-formatter',
    name: 'SQL 格式化',
    nameEn: 'SQL Formatter',
    description: '格式化和美化 SQL 语句，支持多种数据库方言',
    category: 'format',
    tags: ['sql', 'format', 'database', 'mysql', 'postgresql'],
    icon: 'Database',
  },
  {
    id: 'xml-formatter',
    name: 'XML 格式化',
    nameEn: 'XML Formatter',
    description: '格式化、压缩、校验 XML 文档',
    category: 'format',
    tags: ['xml', 'format', 'validate', 'minify'],
    icon: 'Code2',
  },
  {
    id: 'css-formatter',
    name: 'CSS 格式化',
    nameEn: 'CSS Formatter',
    description: 'CSS/SCSS/Less 格式化与压缩',
    category: 'format',
    tags: ['css', 'scss', 'less', 'format', 'minify'],
    icon: 'Paintbrush',
  },
  {
    id: 'js-formatter',
    name: 'JS/TS 格式化',
    nameEn: 'JS/TS Formatter',
    description: 'JavaScript/TypeScript/JSON5 格式化与压缩',
    category: 'format',
    tags: ['javascript', 'typescript', 'json5', 'format', 'minify'],
    icon: 'FileCode',
  },
  {
    id: 'toml-json',
    name: 'TOML ↔ JSON',
    nameEn: 'TOML JSON Converter',
    description: 'TOML 与 JSON 格式互转',
    category: 'format',
    tags: ['toml', 'json', 'convert'],
    icon: 'FileCode2',
  },
  {
    id: 'csv-viewer',
    name: 'CSV 查看器',
    nameEn: 'CSV Viewer',
    description: 'CSV 数据可视化查看与转换',
    category: 'format',
    tags: ['csv', '表格', '数据'],
    icon: 'Table',
  },

  // Encoding - 编码解码
  {
    id: 'html-entities',
    name: 'HTML 实体编解码',
    nameEn: 'HTML Entity Encoder',
    description: 'HTML 实体编码与解码',
    category: 'encoding',
    tags: ['html', 'entity', 'encode', 'decode', 'escape'],
    icon: 'Code2',
  },
  {
    id: 'hex-encode',
    name: 'Hex 编解码',
    nameEn: 'Hex Encoder/Decoder',
    description: '文本与十六进制互转',
    category: 'encoding',
    tags: ['hex', 'encode', 'decode', 'hexadecimal'],
    icon: 'Hash',
  },
  {
    id: 'unicode-convert',
    name: 'Unicode 转换',
    nameEn: 'Unicode Converter',
    description: '字符与 Unicode 码点互转，支持多种表示格式',
    category: 'encoding',
    tags: ['unicode', 'utf', 'codepoint', 'convert'],
    icon: 'Languages',
  },
  {
    id: 'morse-code',
    name: '摩斯密码',
    nameEn: 'Morse Code',
    description: '文本与摩斯电码互转',
    category: 'encoding',
    tags: ['morse', 'code', 'encode', 'decode'],
    icon: 'Radio',
  },
  {
    id: 'binary-text',
    name: '二进制文本',
    nameEn: 'Binary Text',
    description: '文本与二进制字符串互转',
    category: 'encoding',
    tags: ['binary', 'text', 'encode', 'decode'],
    icon: 'Binary',
  },
  {
    id: 'rot13',
    name: 'ROT13/Caesar',
    nameEn: 'ROT13/Caesar Cipher',
    description: 'ROT13 及 Caesar 移位密码，偏移量可调',
    category: 'encoding',
    tags: ['rot13', 'caesar', 'cipher', 'encrypt'],
    icon: 'Lock',
  },
  {
    id: 'punycode',
    name: 'Punycode 转换',
    nameEn: 'Punycode Converter',
    description: '国际化域名 IDN Punycode 编解码',
    category: 'encoding',
    tags: ['punycode', 'idn', 'domain', 'encode', 'decode'],
    icon: 'Globe',
  },
  {
    id: 'ascii-table',
    name: 'ASCII 码表',
    nameEn: 'ASCII Table',
    description: '完整 ASCII/Unicode 字符查询，支持描述搜索',
    category: 'encoding',
    tags: ['ascii', 'table', 'unicode', 'character'],
    icon: 'Table',
  },

  // Crypto - 加密安全
  {
    id: 'aes-encrypt',
    name: 'AES 加密解密',
    nameEn: 'AES Encrypt/Decrypt',
    description: 'AES-GCM 对称加密与解密',
    category: 'crypto',
    tags: ['aes', 'encrypt', 'decrypt', 'crypto', 'symmetric'],
    icon: 'Lock',
  },
  {
    id: 'rsa-keygen',
    name: 'RSA 密钥生成',
    nameEn: 'RSA Key Generator',
    description: '生成 RSA 密钥对，导出 PEM 格式',
    category: 'crypto',
    tags: ['rsa', 'key', 'generate', 'pem', 'asymmetric'],
    icon: 'ShieldCheck',
  },
  {
    id: 'hmac',
    name: 'HMAC 计算',
    nameEn: 'HMAC Calculator',
    description: 'HMAC-SHA256/512 签名计算',
    category: 'crypto',
    tags: ['hmac', 'sha', 'signature', 'verify'],
    icon: 'KeyRound',
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt 哈希',
    nameEn: 'Bcrypt Hash',
    description: 'Bcrypt 密码哈希与验证，rounds 可配置',
    category: 'crypto',
    tags: ['bcrypt', 'hash', 'password', 'verify'],
    icon: 'LockKeyhole',
  },
  {
    id: 'ssh-keygen',
    name: 'SSH 密钥生成',
    nameEn: 'SSH Key Generator',
    description: '生成 Ed25519/RSA SSH 密钥对',
    category: 'crypto',
    tags: ['ssh', 'key', 'ed25519', 'rsa', 'generate'],
    icon: 'Terminal',
  },
  {
    id: 'jwt-generator',
    name: 'JWT 生成',
    nameEn: 'JWT Generator',
    description: '填写 Payload/Header，选择算法生成 Token',
    category: 'crypto',
    tags: ['jwt', 'token', 'generate', 'hs256', 'rs256'],
    icon: 'KeyRound',
  },

  // Network - 网络HTTP
  {
    id: 'ip-lookup',
    name: 'IP 地址查询',
    nameEn: 'IP Lookup',
    description: '查询 IP 地址的地理位置、ASN 等信息',
    category: 'network',
    tags: ['ip', 'lookup', 'geo', 'asn', 'location'],
    icon: 'Globe',
    requiresApi: true,
  },
  {
    id: 'dns-lookup',
    name: 'DNS 查询',
    nameEn: 'DNS Lookup',
    description: '查询域名的 A、AAAA、MX、TXT、CNAME 记录',
    category: 'network',
    tags: ['dns', 'lookup', 'domain', 'mx', 'txt', 'cname'],
    icon: 'Search',
    requiresApi: true,
  },
  {
    id: 'url-parser',
    name: 'URL 解析',
    nameEn: 'URL Parser',
    description: '解析 URL 的各个组成部分',
    category: 'network',
    tags: ['url', 'parse', 'query', 'path', 'hostname'],
    icon: 'Unlink',
  },
  {
    id: 'http-status',
    name: 'HTTP 状态码',
    nameEn: 'HTTP Status Codes',
    description: '查询 HTTP 状态码的含义和说明',
    category: 'network',
    tags: ['http', 'status', 'code', '404', '500', '200'],
    icon: 'Activity',
  },
  {
    id: 'http-headers',
    name: 'HTTP 请求头',
    nameEn: 'HTTP Headers',
    description: '常见请求/响应头说明，安全头建议',
    category: 'network',
    tags: ['http', 'header', 'request', 'response'],
    icon: 'List',
  },
  {
    id: 'mime-types',
    name: 'MIME 类型',
    nameEn: 'MIME Types',
    description: '文件扩展名与 MIME 类型对照查询',
    category: 'network',
    tags: ['mime', 'type', 'extension', 'content-type'],
    icon: 'FileType',
  },
  {
    id: 'ip-subnet',
    name: 'IP 子网计算',
    nameEn: 'IP Subnet Calculator',
    description: 'CIDR 计算网络地址/广播地址/主机数',
    category: 'network',
    tags: ['ip', 'subnet', 'cidr', 'network', 'calculator'],
    icon: 'Network',
  },
  {
    id: 'user-agent',
    name: 'UA 解析',
    nameEn: 'User Agent Parser',
    description: '解析 User-Agent 字符串，识别浏览器/OS/设备',
    category: 'network',
    tags: ['user-agent', 'ua', 'browser', 'device', 'parse'],
    icon: 'Monitor',
  },
  {
    id: 'curl-converter',
    name: 'cURL 转换',
    nameEn: 'cURL Converter',
    description: 'cURL 命令转换为 fetch/axios/Python/Go 代码',
    category: 'network',
    tags: ['curl', 'convert', 'fetch', 'axios', 'python'],
    icon: 'Terminal',
  },

  // Text - 文本处理
  {
    id: 'text-diff',
    name: '文本 Diff',
    nameEn: 'Text Diff',
    description: '对比两段文本的差异，高亮显示',
    category: 'text',
    tags: ['diff', 'compare', 'text', 'difference'],
    icon: 'GitCompare',
  },
  {
    id: 'text-transform',
    name: '文本变换',
    nameEn: 'Text Transform',
    description: '去重/排序/反转/去空行/提取行等批量操作',
    category: 'text',
    tags: ['text', 'transform', 'sort', 'dedupe', 'reverse'],
    icon: 'TextCursorInput',
  },
  {
    id: 'string-escape',
    name: '字符串转义',
    nameEn: 'String Escape',
    description: 'JS/Python/Java/C 字符串转义与反转义',
    category: 'text',
    tags: ['string', 'escape', 'unescape', 'quote'],
    icon: 'Quote',
  },
  {
    id: 'cron-parser',
    name: 'Cron 表达式解析',
    nameEn: 'Cron Parser',
    description: '解析和生成 Cron 表达式，显示下次执行时间',
    category: 'text',
    tags: ['cron', 'schedule', 'parse', 'expression'],
    icon: 'Timer',
  },
  {
    id: 'text-similarity',
    name: '文本相似度',
    nameEn: 'Text Similarity',
    description: '计算两段文本的相似度，基于 Levenshtein 距离',
    category: 'text',
    tags: ['text', 'similarity', 'levenshtein', 'compare'],
    icon: 'GitCompare',
  },
  {
    id: 'line-sorter',
    name: '行处理工具',
    nameEn: 'Line Sorter',
    description: '排序/去重/随机打乱/提取第N行/行号添加',
    category: 'text',
    tags: ['line', 'sort', 'dedupe', 'shuffle', 'extract'],
    icon: 'ListOrdered',
  },
  {
    id: 'json-to-type',
    name: 'JSON 转类型定义',
    nameEn: 'JSON to Type Definition',
    description: 'JSON 一键生成 TypeScript/Go/Python/Kotlin 类型',
    category: 'text',
    tags: ['json', 'typescript', 'go', 'python', 'type', 'generate'],
    icon: 'FileType',
  },

  // Color - 颜色设计
  {
    id: 'css-gradient',
    name: 'CSS 渐变生成器',
    nameEn: 'CSS Gradient Generator',
    description: '可视化生成 CSS 渐变代码',
    category: 'color',
    tags: ['gradient', 'css', 'linear', 'radial', 'color'],
    icon: 'Blend',
  },
  {
    id: 'color-palette',
    name: '配色方案生成',
    nameEn: 'Color Palette Generator',
    description: '输入主色生成类比/互补/三角配色方案',
    category: 'color',
    tags: ['color', 'palette', 'scheme', 'analogous', 'complementary'],
    icon: 'SwatchBook',
  },
  {
    id: 'contrast-checker',
    name: 'WCAG 对比度',
    nameEn: 'WCAG Contrast Checker',
    description: '前景/背景色对比度检测，AA/AAA 级别判定',
    category: 'color',
    tags: ['wcag', 'contrast', 'accessibility', 'color'],
    icon: 'Eye',
  },
  {
    id: 'color-blindness',
    name: '色盲模拟',
    nameEn: 'Color Blindness Simulator',
    description: '模拟 8 种色觉缺陷显示效果',
    category: 'color',
    tags: ['color', 'blindness', 'accessibility', 'simulate'],
    icon: 'Eye',
  },
  {
    id: 'tailwind-colors',
    name: 'Tailwind 色板',
    nameEn: 'Tailwind Colors',
    description: '完整 Tailwind v3/v4 色板，点击复制',
    category: 'color',
    tags: ['tailwind', 'color', 'palette', 'css'],
    icon: 'Palette',
  },
  {
    id: 'box-shadow-gen',
    name: 'Box Shadow 生成',
    nameEn: 'Box Shadow Generator',
    description: '可视化调整 box-shadow，预览并复制 CSS',
    category: 'color',
    tags: ['css', 'shadow', 'box-shadow', 'generator'],
    icon: 'Square',
  },

  // Crypto - 证书
  {
    id: 'cert-decoder',
    name: 'TLS 证书解析',
    nameEn: 'TLS Certificate Decoder',
    description: '解析 PEM 证书，显示域名/有效期/指纹/SAN',
    category: 'crypto',
    tags: ['certificate', 'tls', 'ssl', 'pem', 'x509'],
    icon: 'Shield',
  },

  // Datetime - 时间日期
  {
    id: 'date-calc',
    name: '日期计算器',
    nameEn: 'Date Calculator',
    description: '日期加减/两日期差值，工作日计算',
    category: 'datetime',
    tags: ['date', 'calculator', 'diff', 'add', 'subtract'],
    icon: 'Calendar',
  },
  {
    id: 'timezone-convert',
    name: '时区转换',
    nameEn: 'Timezone Converter',
    description: '全球时区对照，多时区同屏显示',
    category: 'datetime',
    tags: ['timezone', 'convert', 'zone', 'utc'],
    icon: 'Globe',
  },
  {
    id: 'duration-format',
    name: '时长格式化',
    nameEn: 'Duration Formatter',
    description: '秒数与 hh:mm:ss/人话描述互转',
    category: 'datetime',
    tags: ['duration', 'format', 'time', 'convert'],
    icon: 'Timer',
  },
  {
    id: 'calendar-gen',
    name: '日历生成',
    nameEn: 'Calendar Generator',
    description: '生成指定年月日历，支持导出 iCal',
    category: 'datetime',
    tags: ['calendar', 'generate', 'ical', 'month'],
    icon: 'CalendarDays',
  },

  // Generator - 生成器
  {
    id: 'nanoid-gen',
    name: 'NanoID 生成器',
    nameEn: 'NanoID Generator',
    description: '自定义字符集和长度，批量生成',
    category: 'generator',
    tags: ['nanoid', 'generate', 'id', 'unique'],
    icon: 'Fingerprint',
  },
  {
    id: 'ulid-gen',
    name: 'ULID 生成器',
    nameEn: 'ULID Generator',
    description: '时间有序唯一 ID，比 UUID 更友好',
    category: 'generator',
    tags: ['ulid', 'generate', 'id', 'unique', 'time'],
    icon: 'Fingerprint',
  },
  {
    id: 'objectid-gen',
    name: 'MongoDB ObjectID',
    nameEn: 'MongoDB ObjectID Generator',
    description: '生成/解析 ObjectID，显示时间戳和机器码',
    category: 'generator',
    tags: ['objectid', 'mongodb', 'generate', 'parse'],
    icon: 'Fingerprint',
  },
  {
    id: 'faker-data',
    name: '假数据生成',
    nameEn: 'Fake Data Generator',
    description: '姓名/邮箱/手机/地址/公司等假数据生成',
    category: 'generator',
    tags: ['faker', 'fake', 'data', 'generate', 'mock'],
    icon: 'Database',
  },
  {
    id: 'qrcode',
    name: '二维码生成',
    nameEn: 'QR Code Generator',
    description: '生成二维码，支持文本、URL、WiFi 等格式',
    category: 'generator',
    tags: ['qrcode', 'qr', 'generate', 'barcode'],
    icon: 'QrCode',
  },
  {
    id: 'placeholder-img',
    name: '占位图生成',
    nameEn: 'Placeholder Image Generator',
    description: '生成指定尺寸/颜色/文字的占位图',
    category: 'generator',
    tags: ['placeholder', 'image', 'svg', 'generate'],
    icon: 'Image',
  },

  // ─── Phase 3: AI 增强工具 ────────────────────────────────────────────────────

  {
    id: 'ai-regex',
    name: 'AI 正则生成',
    nameEn: 'AI Regex Generator',
    description: '用自然语言描述，AI 自动生成正则表达式并附上解释',
    category: 'ai',
    tags: ['ai', 'regex', 'regexp', 'generate', 'nlp'],
    keywords: ['正则', '自然语言', '生成', '匹配'],
    icon: 'Sparkles',
    requiresApi: true,
    isNew: true,
  },
  {
    id: 'ai-sql',
    name: 'AI SQL 生成',
    nameEn: 'AI SQL Generator',
    description: '自然语言转 SQL，支持提供数据库 Schema 生成精准查询',
    category: 'ai',
    tags: ['ai', 'sql', 'database', 'query', 'generate'],
    keywords: ['数据库', '查询', '生成', 'select'],
    icon: 'Database',
    requiresApi: true,
    isNew: true,
  },
  {
    id: 'ai-code-explain',
    name: 'AI 代码解释',
    nameEn: 'AI Code Explainer',
    description: '粘贴任意代码，AI 用中文为你详细解释逻辑和关键概念',
    category: 'ai',
    tags: ['ai', 'code', 'explain', 'review'],
    keywords: ['代码', '解释', '分析', '理解'],
    icon: 'BookOpen',
    requiresApi: true,
    isNew: true,
  },

  // ─── Phase 3.1: 图片&媒体 (8个) ────────────────────────────────────────────

  {
    id: 'image-compress',
    name: '图片压缩',
    nameEn: 'Image Compress',
    description: 'JPEG/PNG/WebP 图片压缩，质量可调，对比预览，批量处理',
    category: 'image',
    tags: ['image', 'compress', 'jpeg', 'png', 'webp', 'optimize'],
    keywords: ['压缩', '图片优化', '减小体积'],
    icon: 'Minimize',
    isNew: true,
  },
  {
    id: 'image-convert',
    name: '图片格式转换',
    nameEn: 'Image Converter',
    description: 'PNG/JPEG/WebP/GIF 格式转换，含透明通道处理，批量处理',
    category: 'image',
    tags: ['image', 'convert', 'png', 'jpeg', 'webp', 'format'],
    keywords: ['格式转换', '图片', '批量'],
    icon: 'RefreshCw',
    isNew: true,
  },
  {
    id: 'image-resize',
    name: '图片裁剪缩放',
    nameEn: 'Image Resize',
    description: '指定尺寸/比例，填充/裁剪/拉伸模式，批量处理',
    category: 'image',
    tags: ['image', 'resize', 'crop', 'scale', 'batch'],
    keywords: ['缩放', '裁剪', '调整尺寸'],
    icon: 'Crop',
    isNew: true,
  },
  {
    id: 'svg-optimizer',
    name: 'SVG 优化',
    nameEn: 'SVG Optimizer',
    description: '优化 SVG 文件，去除冗余属性和元数据，显示压缩率',
    category: 'image',
    tags: ['svg', 'optimize', 'compress', 'minify', 'vector'],
    keywords: ['矢量', '优化', '压缩', 'svgo'],
    icon: 'Minimize2',
    isNew: true,
  },
  {
    id: 'svg-to-data-uri',
    name: 'SVG → Data URI',
    nameEn: 'SVG to Data URI',
    description: 'SVG 文件转 Data URI/Base64，可内联到 CSS/HTML 中使用',
    category: 'image',
    tags: ['svg', 'data-uri', 'base64', 'inline', 'css', 'html'],
    keywords: ['内联', '转换', '嵌入'],
    icon: 'FileCode',
    isNew: true,
  },
  {
    id: 'favicon-gen',
    name: 'Favicon 生成',
    nameEn: 'Favicon Generator',
    description: '上传图片生成全套 favicon (16/32/48/180px)，下载使用',
    category: 'image',
    tags: ['favicon', 'icon', 'generate', 'png', 'ico', 'apple-touch'],
    keywords: ['图标', '网站图标', '浏览器图标'],
    icon: 'Globe',
    isNew: true,
  },
  {
    id: 'exif-reader',
    name: 'EXIF 数据读取',
    nameEn: 'EXIF Reader',
    description: '读取图片 EXIF 信息：拍摄参数/GPS/设备型号，支持脱敏导出',
    category: 'image',
    tags: ['exif', 'metadata', 'photo', 'gps', 'camera', 'jpeg'],
    keywords: ['元数据', '拍摄信息', '照片', '相机'],
    icon: 'Camera',
    isNew: true,
  },
  {
    id: 'color-extractor',
    name: '图片取色',
    nameEn: 'Color Extractor',
    description: '上传图片提取主色调，生成配色板，支持 Hex/RGB 复制',
    category: 'image',
    tags: ['color', 'extract', 'palette', 'dominant', 'image', 'picker'],
    keywords: ['取色', '配色', '主色调', '颜色提取'],
    icon: 'Pipette',
    isNew: true,
  },

  // ─── Phase 3.2: 开发规范&文档 (7个) ─────────────────────────────────────────

  {
    id: 'gitignore-gen',
    name: '.gitignore 生成',
    nameEn: '.gitignore Generator',
    description: '选择语言/框架/IDE，生成最佳实践 .gitignore 文件',
    category: 'devops',
    tags: ['gitignore', 'git', 'generate', 'template', 'node', 'python'],
    keywords: ['忽略文件', 'git', '模板'],
    icon: 'GitBranch',
    isNew: true,
  },
  {
    id: 'license-gen',
    name: 'License 生成',
    nameEn: 'License Generator',
    description: 'MIT/Apache/GPL/BSD/ISC 等开源协议，填入作者/年份，下载 LICENSE 文件',
    category: 'devops',
    tags: ['license', 'mit', 'apache', 'gpl', 'bsd', 'open source'],
    keywords: ['开源协议', '许可证', '版权'],
    icon: 'Scale',
    isNew: true,
  },
  {
    id: 'readme-gen',
    name: 'README 生成',
    nameEn: 'README Generator',
    description: 'Markdown README 模板生成器，徽章选择，章节自由组合',
    category: 'devops',
    tags: ['readme', 'markdown', 'template', 'badge', 'documentation'],
    keywords: ['说明文档', '项目文档', '徽章'],
    icon: 'FileText',
    isNew: true,
  },
  {
    id: 'conventional-commit',
    name: '提交信息生成',
    nameEn: 'Conventional Commit',
    description: 'Conventional Commits 格式提交信息生成器，选择类型/scope/描述',
    category: 'devops',
    tags: ['git', 'commit', 'conventional', 'message', 'changelog'],
    keywords: ['提交', 'commit message', 'git提交'],
    icon: 'GitCommit',
    isNew: true,
  },
  {
    id: 'semver-calc',
    name: 'SemVer 计算器',
    nameEn: 'SemVer Calculator',
    description: '语义版本范围计算，^/>=/<=解析，版本对比与排序',
    category: 'devops',
    tags: ['semver', 'version', 'semantic', 'npm', 'range'],
    keywords: ['语义版本', '版本号', 'npm版本'],
    icon: 'Tag',
    isNew: true,
  },
  {
    id: 'openapi-viewer',
    name: 'OpenAPI 查看器',
    nameEn: 'OpenAPI Viewer',
    description: '上传 swagger.json/yaml，可视化展示 API 文档，支持 OpenAPI 3.x',
    category: 'devops',
    tags: ['openapi', 'swagger', 'api', 'docs', 'rest', 'yaml', 'json'],
    keywords: ['API文档', 'swagger', '接口文档'],
    icon: 'BookOpen',
    isNew: true,
  },
  {
    id: 'json-schema-gen',
    name: 'JSON Schema 生成',
    nameEn: 'JSON Schema Generator',
    description: 'JSON 数据自动反推 JSON Schema，支持可选字段标注',
    category: 'devops',
    tags: ['json', 'schema', 'generate', 'validation', 'typescript'],
    keywords: ['模式推断', 'json验证', 'schema生成'],
    icon: 'FileJson',
    isNew: true,
  },
]

export const searchIndex = new Fuse(toolRegistry, {
  keys: [
    { name: 'name',        weight: 0.4 },
    { name: 'nameEn',      weight: 0.3 },
    { name: 'tags',        weight: 0.2 },
    { name: 'description', weight: 0.05 },
    { name: 'keywords',    weight: 0.05 },
  ],
  threshold: 0.35,
  includeScore: true,
})

export function searchTools(query: string): ToolMeta[] {
  if (!query.trim()) return toolRegistry
  return searchIndex.search(query).map(r => r.item)
}

export function getToolsByCategory(category: string): ToolMeta[] {
  return toolRegistry.filter(t => t.category === category)
}

export function getToolById(id: string): ToolMeta | undefined {
  return toolRegistry.find(t => t.id === id)
}
